### ISSUE TITLE
Dropdown buttons overlay dropdown itself

### ISSUE THREAD

**Issue by vertex** [gabrielcsapo/psychic-ui#14]
Dropdowns z-indexing is messed up
![screen shot 2016-05-03 at 10 33 32 am](https://cloud.githubusercontent.com/assets/59979/14992379/b3c2ff8a-111a-11e6-80c0-ba9c1a7882b8.png)

**Comment by gabrielcsapo** [comment]
👍 will check it out, thank you!

**Comment by gabrielcsapo** [comment]
@vertex this was fixed in #15, a gif has been attached to show the fix 😸
